/**
 * `npm run small-rules`: regenerate `shared/game/brains/small-rules.ts` —
 * every clean rule whose lines all stay short (no strand over `CAP` steps,
 * on level 4 and level 5 alike), with its longest strand. The Edge Lords
 * skip the ones under `EDGE_LORD_MIN_STRAND` (`brains/kinds.ts`): an edge
 * line there is a few tiles long and nothing nests.
 *
 * Every combination of every clean subset is measured but each family's
 * full subset (hex `01234568`: 1,953,125 combos; spectre `01235678`:
 * 625,000), which none of the ~3,400 hex full-rule combos sampled
 * comes near: their longest strand at level 4 is 80 steps or more and grows
 * with the board. A bot rolling a full-subset rule is never skipped.
 * A minute or two.
 */

import { writeFileSync } from 'node:fs';
import { buildField } from '../shared/game/field';
import { chordTableFor } from '../shared/game/strand';
import { describeRule, type PlayerRule } from '../shared/game/rule';
import { longestStrand } from '../shared/game/brains/sense';
import { leafOrder, nonCrossingForTile, validEdgeSubsets, type TileFamilyId } from '../shared/tiles';

/** Longest strand worth recording, in steps. */
export const CAP = 64;
const FAMILIES: readonly TileFamilyId[] = ['hex', 'spectre'];
const OUT = new URL('../shared/game/brains/small-rules.ts', import.meta.url);

/** Every rule of `family` on a clean subset other than the full one. */
export function enumerableRules(family: TileFamilyId): PlayerRule[] {
  const subsets = validEdgeSubsets(family).filter((v) => v.edges.length > 0);
  const full = Math.max(...subsets.map((v) => v.edges.length));
  const rules: PlayerRule[] = [];
  for (const v of subsets) {
    if (v.edges.length === full) continue;
    const selected = new Set(v.edges);
    const options = leafOrder(family).map((t) => {
      const ok = nonCrossingForTile(family, t, selected);
      return ok.length ? ok : [0];
    });
    const walk = (i: number, acc: number[]): void => {
      if (i === options.length) {
        rules.push({ family, subset: v.edges, matching: [...acc] });
        return;
      }
      for (const m of options[i]) {
        acc.push(m);
        walk(i + 1, acc);
        acc.pop();
      }
    };
    walk(0, []);
  }
  return rules;
}

function main(): void {
  const lines: string[] = [];
  for (const family of FAMILIES) {
    const small = buildField({ family, level: 4, rootTile: 'Delta' });
    const big = buildField({ family, level: 5, rootTile: 'Delta' });
    const rules = enumerableRules(family);
    const found: [string, number][] = [];
    for (const rule of rules) {
      const a = longestStrand(small, chordTableFor(small, rule), CAP);
      if (a > CAP) continue;
      const b = longestStrand(big, chordTableFor(big, rule), CAP);
      if (b === a) found.push([describeRule(rule), b]);
    }
    found.sort((x, y) => x[1] - y[1] || (x[0] < y[0] ? -1 : 1));
    process.stderr.write(`${family}: ${found.length} of ${rules.length} combos stay under ${CAP + 1} steps\n`);
    lines.push(`  ${family}: {`, ...found.map(([k, n]) => `    '${k}': ${n},`), '  },');
  }
  writeFileSync(
    OUT,
    [
      '// Generated by `npm run small-rules` (scripts/small-rules.ts) — do not edit by hand.',
      '//',
      `// Every clean rule, but each family's full subset, whose lines all stay short:`,
      `// no circuit, tail or edge line over ${CAP} steps on a level-4 board, and the same`,
      '// on level 5 (so it never grows). Value: its longest strand, in steps.',
      '// Keyed like `describeRule`.',
      '',
      'export const SMALL_RULES: Readonly<Record<string, Readonly<Record<string, number>>>> = {',
      ...lines,
      '};',
      '',
    ].join('\n'),
  );
}

if (import.meta.url === `file://${process.argv[1]}`) main();
